In [98]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager

##### Extract, Transform, and Load

In [95]:
def extract(page):
    headers = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36'}
    url = ''
    if page == 0:
        url = 'https://www.indeed.com/jobs?q=data+analyst&jt=fulltime&explvl=entry_level&fromage=7'
    else:
        url = f'https://www.indeed.com/jobs?q=data+analyst&jt=fulltime&explvl=entry_level&fromage=7&start={page}'
    
    response = requests.get(url,headers)
    soup = BeautifulSoup(response.content, 'html.parser')

    return soup

In [114]:
def transform(soup):

    divs = soup.find_all('div', class_='job_seen_beacon')
    for item in divs:
        title = item.find('h2').text.split('new')[1].strip()
        company = item.find('span', class_='companyName').text.strip()
        summary = item.find('li').text.strip().replace('\n', '')
        day = item.find('span', class_='date').text.strip()
        try:
            attribute = item.find('div', class_='attribute_snippet').text.strip()
        except:
            attribute = ''
        
        job = {
            'title' : title,
            'company': company,
            'summary': summary,
            'attribute':attribute
        }
        #joblist.append(job)
        print(day)

EmployerActive 3 days ago
Posted1 day ago
PostedToday
Posted5 days ago
PostedJust posted
Posted2 days ago
PostedToday
PostedToday
PostedToday
Posted1 day ago
PostedToday
Posted6 days ago
Posted2 days ago
Posted2 days ago
PostedToday

In [108]:
joblist = []
for i in range(0,40,5):
    info_extracted = extract(i)
    transform(info_extracted)
df = pd.DataFrame(joblist)
df

,title,company,summary,attribute
0,Data Analyst,Kinetic Personnel Group Inc.,Reviews and validates data entry across all da...,"$60,000 - $70,000 a year"
1,Data Analyst,DISYS,Knowledge of data management policies and proc...,$38 an hour
2,Data Analyst/Remote,CDC Foundation ( Contract),"Perform basic data management, data cleaning a...","$66,000 - $72,000 a year"
3,Data Analyst,System Innovators,Develop database objects and scripts to load d...,Full-time
4,"Analyst, Data",Molina Healthcare,Job Summary Designs and implements processes a...,Full-time
...,...,...,...,...
115,Business Analyst,Inrika Inc.,Strong verbal and written communication skills...,"$60,000 - $120,000 a year"
116,Policy Analyst,"Federal Finnancial Analytics, Inc.",Gather and analyze data from public sources.,"From $65,000 a year"
117,Data Quality Analyst,"Blackline Group, Inc.",Identify data quality improvement opportunitie...,"$60,000 - $65,000 a year"
118,Data Analyst - RI Irwin,Nationwide Children's Hospital,"Supports Research data activities, including p...",
119,Data Analyst I,Neogen,As time allows work to streamline data analysi...,

In [111]:
df.to_csv('indeed_jobs.csv', index=False)